### ISSUE TITLE
Readme required for starting app

### ISSUE THREAD

**Issue by wasimekram** [HackerHaze/GPT-linkedin-apply#1]
Hi, I am a python developer and haven't used much of javascript.
Can you please upload the readme with steps to install the requirements and how to run the file?
You could also upload the docker container for it if possible.

**Comment by mattwebhub** [comment]
> Hi, I am a python developer and haven't used much of javascript.
> Can you please upload the readme with steps to install the requirements and how to run the file?
> You could also upload the docker container for it if possible.

Sure

**Comment by wasimekram** [comment]
Hi @mattwebhub 
There's an issue while compiling the tsconfig file

It can't find the 'config' folder and 'scrape' folder

Executing task: /Users/user/Documents/projects/GPT-linkedin-apply/node_modules/.bin/tsc -p /Users/user/Documents/projects/GPT-linkedin-apply/tsconfig.json 

agent/app.ts:3:10 - error TS2614: Module '"."' has no exported member 'testFunctions'. Did you mean to use 'import testFunctions from "."' instead?

3 import { testFunctions } from ".";
           ~~~~~~~~~~~~~

agent/index.ts:2:10 - error TS2614: Module '"./scrape"' has no exported member 'getAllTabbableElements'. Did you mean to use 'import getAllTabbableElements from "./scrape"' instead?

2 import { getAllTabbableElements, getPageContent } from "./scrape";
           ~~~~~~~~~~~~~~~~~~~~~~

agent/index.ts:2:34 - error TS2614: Module '"./scrape"' has no exported member 'getPageContent'. Did you mean to use 'import getPageContent from "./scrape"' instead?

2 import { getAllTabbableElements, getPageContent } from "./scrape";
                                   ~~~~~~~~~~~~~~

agent/services/sendChatMessage.ts:3:29 - error TS2307: Cannot find module '../config' or its corresponding type declarations.

3 import { definitions } from "../config";
                              ~~~~~~~~~~~


Found 4 errors in 3 files.

Errors  Files
     1  agent/app.ts:3
     2  agent/index.ts:2
     1  agent/services/sendChatMessage.ts:3

 *  The terminal process "/bin/zsh '-l', '-c', '/Users/user/Documents/projects/GPT-linkedin-apply/node_modules/.bin/tsc -p /Users/user/Documents/projects/GPT-linkedin-apply/tsconfig.json'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by mattwebhub** [comment]
@wasimekram I'll be taking this on this weekend and working on a v2 for this repo soon
